### ISSUE TITLE
Update README.md for Node.js Runtime 12!

### ISSUE THREAD

**Issue by nelsonic** [dwyl/aws-lambda-deploy#65]
Since we last updated this package AWS has released support for the Node.js `v12` (LTS)!
https://aws.amazon.com/blogs/compute/node-js-12-x-runtime-now-available-in-aws-lambda
That means we no longer need to use **`babel`** in order to use `ES6` / `ES2016+` 🎉 

## Todo

+ [x] ***remove*** all references to **`babel`** from `README.md`
+ [x] ***remove*** all babel related modules from `devDependencies` #64 
![aws-lambda-deploy-babel](https://user-images.githubusercontent.com/194400/73841985-a0593200-4813-11ea-825c-73ec3f0b80a9.png)
+ [x] ***test*** deploying a Lambda function containing `ES6` using  Node.js `v12`

**Comment by nelsonic** [comment]
Included in #66 📦

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/74257905-642f4100-4ced-11ea-9771-a7a391ee0ecb.png)

Deployed a couple of Lambda Functions:
![aws-lambda-functions-deployed](https://user-images.githubusercontent.com/194400/74257981-7dd08880-4ced-11ea-9109-ad3fd67a86fd.png)

**Comment by nelsonic** [comment]
Next update: #85 -> #86
