### ISSUE TITLE
Use Travis CI instead of CodeShip

### ISSUE THREAD

**Issue by nelsonic** [dwyl/aws-lambda-deploy#67]
At present this repo is using CodeShip for CI. 
See: https://github.com/dwyl/aws-lambda-deploy/blame/0a391ed9158834bcb65f9acb0e74623a007f0ade/README.md#L6
This was because back in the day the client we were working with insisted we use CodeShip.
The _disadvantage_ of codeship is that it has no public build log so it's quite difficult to debug.

# Todo
+ [x] Setup Travis-CI for this repo. see: https://github.com/dwyl/learn-travis#how
+ [x] Use _encrypted_ environment variables for AWS keys in the `.travis.yml` file.
see: https://github.com/dwyl/learn-travis#3-secure-encrypted-environment-variables 
+ [x] Update `README.md` badges once it's working!

**Comment by nelsonic** [comment]
The build was failing because Travis-CI was running _two_ builds simultaneously 
(_one for the PR the other for the branch_) 
That meant that the Lambda function that was not mean to _exist_ was created by one build and then the other build would fail ... 🤦‍♂ 
So I had to use the "limit concurrent jobs" setting to only run _one_ build at a time
see: https://docs.travis-ci.com/user/customizing-the-build/#limiting-concurrent-jobs

**Comment by nelsonic** [comment]
Each commit on the branch runs _four_ builds on Travis-CI: 🤷‍♂ 
![image](https://user-images.githubusercontent.com/194400/74196603-7fe70880-4c55-11ea-8dd2-9e4e19fbcb17.png)
Kinda painful if you're waiting for them to run in series ... ⏳

**Comment by nelsonic** [comment]
The PR build passes:
![image](https://user-images.githubusercontent.com/194400/74223278-3f67a900-4cae-11ea-9655-0d445c0e31d4.png)

But then the _branch_ build times out: 
https://travis-ci.com/dwyl/aws-lambda-deploy/jobs/285794777#L351
![image](https://user-images.githubusercontent.com/194400/74223418-8eadd980-4cae-11ea-926a-5bb1c85d606c.png)

**Comment by nelsonic** [comment]
This is _so_ frustrating! All the ***ODD*** numbered builds for the PR pass:
![image](https://user-images.githubusercontent.com/194400/74224839-7e4b2e00-4cb1-11ea-9732-168633cbe845.png)

But the ***EVEN*** numbered ones for the branch _fail_. 😞

**Comment by nelsonic** [comment]
This is a bit more informative ...
![image](https://user-images.githubusercontent.com/194400/74227463-6b872800-4cb6-11ea-81a5-0080bb57fa8a.png)
```
Error [CredentialsError]: Missing credentials in config
    at IncomingMessage.<anonymous> (/home/travis/build/dwyl/aws-lambda-deploy/node_modules/aws-sdk/lib/util.js:895:34)
    at IncomingMessage.emit (events.js:228:7)
    at IncomingMessage.EventEmitter.emit (domain.js:475:20)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  message: 'Missing credentials in config',
  statusCode: 404,
  retryable: false,
  time: 2020-02-11T10:03:12.200Z,
  code: 'CredentialsError',
  originalError: {
    message: 'Could not load credentials from any providers',
    statusCode: 404,
    retryable: false,
    time: 2020-02-11T10:03:12.200Z,
    code: 'CredentialsError',
    originalError: {
      message: 'EC2 Metadata roleName request returned error',
      statusCode: 404,
      retryable: false,
      time: 2020-02-11T10:03:12.200Z
    }
  }
} null
```
but it's still not very helpful ... 

Scrolling to the _top_ of the build log we see that the _encrypted_ environment variables aren't loaded!
![image](https://user-images.githubusercontent.com/194400/74227742-03851180-4cb7-11ea-9e7d-a0adb10ea008.png)

Whereas on the PR it works:
![image](https://user-images.githubusercontent.com/194400/74227796-21eb0d00-4cb7-11ea-8554-50e6b8e2b8d6.png)

**Comment by nelsonic** [comment]
Using both the repository and `.travis.yml` environment variables:
![image](https://user-images.githubusercontent.com/194400/74232498-d5a4ca80-4cc0-11ea-8447-6174038efe30.png)

But for some reason, it _still_ does not work on the ***even*** branch:
![image](https://user-images.githubusercontent.com/194400/74232613-13a1ee80-4cc1-11ea-88ca-e7f3a50533b1.png)

No AWS secret keys:
![image](https://user-images.githubusercontent.com/194400/74232586-0422a580-4cc1-11ea-9028-afe49ad873f0.png)

**Comment by nelsonic** [comment]
Got the Travis Build working consistently after switching to Tape! #68 
See PR #66
